logging_config:
  disable_existing_loggers: true
  formatters:
    simple:
      datefmt: "%m-%d-%Y %H:%M:%S"
      format: "%(asctime)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      filename: application.log
      formatter: simple
  loggers:
    main:
      handlers:
        - console
        - file
      level: INFO
      propagate: false
  root:
    handlers:
      - console
    level: WARNING
  version: 1
